### ISSUE TITLE
Need to clean the default parsers in cache directory after modified grammar

### ISSUE THREAD

**Issue by yig** [pressureless/linear_algebra#24]
I modified the grammar, you need to clean the default parsers in cache directory.

_Originally posted by @pressureless in https://github.com/pressureless/linear_algebra/issues/21#issuecomment-720127057_

**Comment by yig** [comment]
A couple of possible solutions:

1. The hash in the filename could be a hash of the entire contents of the grammar files as a string.
2. When loading a grammar, always check the file modification times before accepting the cached version.

**Comment by pressureless** [comment]
App user on Mac(with release version) should have no trouble now since I compare the timestamps and remove the old parsers from cache directory.
But developer still has the problem if the grammar is modified but the parsers under ```la_local_parsers``` are not updated. One naive way would be every time when I modify the grammar, I update the new parsers and push them. But there's no need to push parsers frequently.
I didn't use the entire content for hash value since I thought the content may be too long.

**Comment by yig** [comment]
That's good. So when you update the grammar, everything is fine if you run the `la_local_parsers.py` script before you push, right?

My guess is that the entire content won't be too long. You could even hash each grammar file separately, concatenate the hashes, and then has that. git takes hashes of the entire contents of every file. It's fast, even though it's written in shell scripts.

**Comment by pressureless** [comment]
Yes, `la_local_parsers.py` can still generate new parsers.

OK. I'll try that later.

**Comment by pressureless** [comment]
It won't generate new grammar files now
